
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int AND = 26;
  public static final int RET = 2;
  public static final int LT = 24;
  public static final int NE = 23;
  public static final int IDENT = 30;
  public static final int ELSE = 8;
  public static final int PLUS = 14;
  public static final int INT = 31;
  public static final int OR = 27;
  public static final int RPAREN = 19;
  public static final int EQUAL = 12;
  public static final int WHILE = 9;
  public static final int NOT = 28;
  public static final int Q = 33;
  public static final int PERIOD = 11;
  public static final int MUTABLE = 13;
  public static final int INTCONST = 29;
  public static final int REF = 32;
  public static final int IF = 7;
  public static final int NIL = 34;
  public static final int GT = 25;
  public static final int LPAREN = 18;
  public static final int LBRACKET = 4;
  public static final int LE = 20;
  public static final int RBRACKET = 5;
  public static final int COMMA = 10;
  public static final int EOF = 0;
  public static final int SEMICOL = 3;
  public static final int GE = 21;
  public static final int MINUS = 15;
  public static final int PRINT = 6;
  public static final int error = 1;
  public static final int EQ = 22;
  public static final int UMINUS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RET",
  "SEMICOL",
  "LBRACKET",
  "RBRACKET",
  "PRINT",
  "IF",
  "ELSE",
  "WHILE",
  "COMMA",
  "PERIOD",
  "EQUAL",
  "MUTABLE",
  "PLUS",
  "MINUS",
  "TIMES",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "LE",
  "GE",
  "EQ",
  "NE",
  "LT",
  "GT",
  "AND",
  "OR",
  "NOT",
  "INTCONST",
  "IDENT",
  "INT",
  "REF",
  "Q",
  "NIL"
  };
}

